misc: bring RISC-V to the table (#54)

diff --git a/.github/workflows/deploy_documentation.yml b/.github/workflows/deploy_documentation.yml
--- a/.github/workflows/deploy_documentation.yml
+++ b/.github/workflows/deploy_documentation.yml
@@ -1,89 +1,73 @@
 ---
 # gratefully copied and adjusted from docker-mailserver/docker-mailserver
-name: Documentation
+name: Deploy Documentation
 
 on: # yamllint disable-line rule:truthy
   workflow_dispatch:
   push:
-    branches:
-      - master
+    branches: [master]
     paths:
       - .github/workflows/documentation.yml
       - documentation/**
-    tags:
-      - '[0-9]+.[0-9]+*'
+    tags: ['[0-9]+.[0-9]+*']
 
-defaults:
-  run:
-    shell: bash
+permissions:
+  contents: write
 
 env:
   DOCS_VERSION: edge
-  # Assign commit authorship to official Github Actions
-  # bot when pushing to the `gh-pages` branch:
-  GIT_USER: github-actions[bot]
-  GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
+  CACHE_ID: unknown
 
 jobs:
   deployment:
     name: Deploy documentation
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2.4.0
+        uses: actions/checkout@v4
+
+      - name: Setup Python 3
+        uses: actions/setup-python@v4
         with:
-          submodules: true
+          python-version: 3.x
+
+      - name: Prepare CACHE_ID
+        run: echo "CACHE_ID=$(date --utc '+%V')" >>"${GITHUB_ENV}"
+
+      - name: Setup cache
+        uses: actions/cache@v3
+        with:
+          key: mkdocs-material-${{ env.CACHE_ID }}
+          path: .cache
+          restore-keys: |
+            mkdocs-material-
+
+      - name: Install Python dependencies
+        run: pip install mkdocs-material
 
       - name: Check if deploy is for a `v<major>.<minor>` tag version instead of `edge`
         if: startsWith(github.ref, 'refs/tags/')
         working-directory: documentation
         run: |
           DOCS_VERSION=$(grep -oE 'v[0-9]+\.[0-9]+' <<< "${GITHUB_REF}")
-          echo "DOCS_VERSION=${DOCS_VERSION}" >> "${GITHUB_ENV}"
+          echo "DOCS_VERSION=${DOCS_VERSION}" >>"${GITHUB_ENV}"
           # Docs should build referencing the tagged version instead:
           sed -i "s|^\(site_url:.*\)edge|\1${DOCS_VERSION}|" config.yml
 
-      - name: Build with mkdocs-material with Docker
-        run: scripts/documentation.sh build
-
-      - name: If a tagged version, fix canonical links and remove `404.html`
-        if: startsWith(github.ref, 'refs/tags/')
-        working-directory: documentation/site
-        # 404 is not useful due to how Github Pages implement custom 404 support:
-        # (Note the edge 404.html isn't useful either as it's not copied to
-        # the `gh-pages` branch root)
-        #
-        # Replace the tagged '${DOCS_VERSION}' in the 'canonical' link element of HTML files,
-        # to point to the 'edge' version of documentation as the authoritative source:
-        run: |
-          rm 404.html
-          find . -type f -name "*.html" -exec \
-            sed -i "s|^\(.*<link rel=\"canonical\".*\)${DOCS_VERSION}|\1edge|" {} +
-
-      - name: Deploy to Github Pages
-        uses: peaceiris/actions-gh-pages@v3.8.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          # Build directory contents to publish to the `gh-pages` branch:
-          publish_dir: ./documentation/site
-          # Directory to place `publish_dir` contents on the `gh-pages` branch:
-          destination_dir: ${{ env.DOCS_VERSION }}
-          user_name: ${{ env.GIT_USER }}
-          user_email: ${{ env.GIT_EMAIL }}
+      - name: Deploy documentation
+        run: mkdocs gh-deploy --strict
 
   add-version-to-documentation:
     name: Update `versions.json` if necessary
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
     if: startsWith(github.ref, 'refs/tags/')
     needs: deployment
     steps:
       - name: Checkout the tagged commit (shallow clone)
-        uses: actions/checkout@v2.4.0
-        with:
-          submodules: true
+        uses: actions/checkout@v4
 
-      - name: Checkout the documentation deployment branch to a subdirectory
-        uses: actions/checkout@v2.4.0
+      - name: Checkout the docs deployment branch to a subdirectory
+        uses: actions/checkout@v4
         with:
           ref: gh-pages
           path: gh-pages
@@ -93,13 +77,58 @@ jobs:
         id: add-version
         continue-on-error: true
         working-directory: gh-pages
-        run: ../scripts/documentation.sh update_versions_json
+        run: |
+          MAJOR_MINOR=$(grep -oE 'v[0-9]+\.[0-9]+' <<< "${GITHUB_REF}")
+          echo "DOCS_VERSION=${MAJOR_MINOR}" >>"${GITHUB_ENV}"
+
+          if [[ -z "${MAJOR_MINOR}" ]]; then
+            echo "Could not extract valid \`v<MAJOR>.<MINOR>\` substring, exiting.."
+            exit 1
+          fi
+
+          VERSIONS_JSON='versions.json'
+          IS_VALID=$(jq '.' "${VERSIONS_JSON}")
+
+          if [[ ! -f "${VERSIONS_JSON}" ]] || [[ -z "${IS_VALID}" ]]
+          then
+            echo "'${VERSIONS_JSON}' doesn't exist or is invalid. Creating.."
+            echo '[{"version": "edge", "title": "edge", "aliases": []}]' > "${VERSIONS_JSON}"
+          fi
+
+          # Only add this tag version the first time it's encountered:
+          VERSION_EXISTS=$(jq --arg version "${MAJOR_MINOR}" '[.[].version == $version] | any' "${VERSIONS_JSON}")
+
+          if [[ ${VERSION_EXISTS} == "true" ]]
+          then
+            echo "${MAJOR_MINOR} docs are already supported. Nothing to change, exiting.."
+            exit 1
+          else
+            echo "Added support for ${MAJOR_MINOR} docs."
+            # Add any logic here if you want the version selector to have a different label (`title`) than the `version` URL/subdirectory.
+            TITLE=${TITLE:-${MAJOR_MINOR}}
+
+            # Assumes the first element is always the "latest" unreleased version (`edge` for us), and then newest version to oldest.
+            # `jq` takes the first array element of array as slice, concats with new element, then takes the slice of remaining original elements to concat.
+            # Thus assumes this script is always triggered by newer versions, no older major/minor releases as our build workflow isn't setup to support rebuilding older docs.
+            UPDATED_JSON=$(jq --arg version "${MAJOR_MINOR}" --arg title "${TITLE}" \
+              '.[:1] + [{version: $version, title: $title, aliases: []}] + .[1:]' \
+              "${VERSIONS_JSON}"
+            )
+
+            # See `jq` FAQ advising this approach to update file:
+            # https://github.com/stedolan/jq/wiki/FAQ
+            echo "${UPDATED_JSON}" >tmp.json && mv tmp.json "${VERSIONS_JSON}"
+          fi
 
       # If an actual change was made to `versions.json`, commit and push it.
       # Otherwise the step is skipped instead of reporting job failure.
-      - name: Push update for `versions.json`
+      - name: 'Push update for `versions.json`'
         if: ${{ steps.add-version.outcome == 'success' }}
         working-directory: gh-pages
+        env:
+          # Assign commit authorship to official Github Actions bot when pushing to the `gh-pages` branch:
+          GIT_USER: 'github-actions[bot]'
+          GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
         run: |
           git config user.name ${{ env.GIT_USER }}
           git config user.email ${{ env.GIT_EMAIL }}
